services:
    kfo-server:
        build: .
        image: kfo-server
        ports:
            - 27016:27016
            - 50001:50001
        volumes:
            - ./storage:/app/storage
            - ./logs:/app/logs
            - ./config:/app/config
        restart: unless-stopped

